# Generated by Django 5.2 on 2025-11-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_material_materialrequest_requestitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequest",
            name="desired_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="materialrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Đang mở"),
                    ("offered", "Đã có nhà cung cấp gửi đề nghị"),
                    ("approved", "Đã duyệt"),
                    ("completed", "Hoàn thành"),
                    ("cancelled", "Đã hủy"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
