# Generated by Django 5.2 on 2025-12-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_materialrequest_desired_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flowercategory",
            options={
                "verbose_name": "Danh mục hoa",
                "verbose_name_plural": "Các danh mục hoa",
            },
        ),
        migrations.AlterModelOptions(
            name="floweritem",
            options={"verbose_name": "Hoa", "verbose_name_plural": "Các loại hoa"},
        ),
        migrations.RemoveField(
            model_name="floweritem",
            name="price",
        ),
        migrations.RemoveField(
            model_name="floweritem",
            name="supplier",
        ),
    ]
