# Generated by Django 5.2 on 2026-01-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_alter_flowercategory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flowercategory",
            options={
                "verbose_name": "Danh mục hoa lẻ",
                "verbose_name_plural": "Các danh mục hoa lẻ",
            },
        ),
    ]
