# Generated by Django 5.2 on 2025-11-28 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_material_materialrequest_requestitem"),
        ("supplier_portal", "0002_alter_supplierprofile_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplieroffer",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="inventory.materialrequest",
            ),
        ),
    ]
