# Generated by Django 5.2 on 2025-11-29 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier_portal", "0003_alter_supplieroffer_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplieroffer",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="supplier_portal.materialrequest",
            ),
        ),
    ]
