# Generated by Django 5.2 on 2025-12-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier_portal", "0004_alter_supplieroffer_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestitem",
            name="desired_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Giá mà shop mong muốn nhà cung cấp báo/nhập (ví dụ VNĐ).",
                max_digits=12,
                null=True,
            ),
        ),
    ]
