# Generated by Django 5.2 on 2025-12-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier_portal", "0005_requestitem_desired_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="unit",
            field=models.CharField(
                choices=[
                    ("bo", "bó"),
                    ("canh", "cành"),
                    ("la", "lá"),
                    ("cong", "cọng"),
                    ("nhanh", "nhánh"),
                    ("chiec", "chiếc"),
                    ("cai", "cái"),
                    ("hop", "hộp"),
                    ("khay", "khay"),
                    ("ke", "kệ"),
                    ("tui", "túi"),
                    ("goi", "gói"),
                    ("bich", "bịch"),
                    ("set", "set"),
                    ("bo_set", "bộ"),
                    ("cuon", "cuộn"),
                    ("kg", "kg"),
                    ("g", "g"),
                    ("m", "m"),
                    ("cm", "cm"),
                    ("pallet", "pallet"),
                ],
                default="bo",
                max_length=20,
            ),
        ),
    ]
