# Generated by Django 5.2 on 2025-12-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier_portal", "0006_alter_material_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Đang mở"),
                    ("offered", "Đã có nhà cung cấp gửi đề nghị"),
                    ("approved", "Đã duyệt"),
                    ("completed", "Hoàn thành"),
                    ("closed", "Đã tắt / Ngưng xử lý"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
