# Generated by Django 5.2 on 2025-12-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier_portal", "0007_alter_materialrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Đang mở"),
                    ("approved", "Đã duyệt"),
                    ("completed", "Hoàn thành"),
                    ("closed", "Đã tắt / Ngưng xử lý"),
                    ("rejected", "Đã từ chối"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
