# Generated by Django 5.2 on 2025-12-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "supplier_portal",
            "0009_alter_materialrequest_status_supplierinvoice_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequest",
            name="failure_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="materialrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Đang mở"),
                    ("completed", "Hoàn thành"),
                    ("closed", "Đã tắt / Ngưng xử lý"),
                    ("delivery_failed", "Giao hàng thất bại"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
