# Generated by Django 5.2 on 2025-12-13 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier_portal", "0010_materialrequest_failure_reason_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplierinvoiceitem",
            name="line_total",
        ),
        migrations.AddField(
            model_name="supplierinvoice",
            name="vat_percent",
            field=models.DecimalField(
                decimal_places=2, default=10, help_text="Phần trăm VAT", max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="stockoutitem",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="supplier_portal.material",
            ),
        ),
        migrations.AlterField(
            model_name="stockoutitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="supplierinvoiceitem",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="supplier_portal.material",
            ),
        ),
        migrations.AlterField(
            model_name="supplierinvoiceitem",
            name="received_qty",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="supplierinvoiceitem",
            name="requested_qty",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="supplierinvoiceitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
