# Generated by Django 5.2 on 2025-12-13 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier_portal", "0011_remove_supplierinvoiceitem_line_total_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplierinvoice",
            name="note",
        ),
        migrations.AddField(
            model_name="supplierinvoice",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="supplierinvoice",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="supplierinvoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="supplierinvoice",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="supplier_portal.supplieroffer",
            ),
        ),
        migrations.AlterField(
            model_name="supplierinvoice",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="invoices/"),
        ),
        migrations.AlterField(
            model_name="supplierinvoice",
            name="request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="supplier_portal.materialrequest",
            ),
        ),
        migrations.AlterField(
            model_name="supplierinvoice",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="supplier_portal.supplierprofile",
            ),
        ),
        migrations.AlterField(
            model_name="supplierinvoice",
            name="vat_percent",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="supplierinvoiceitem",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="supplier_portal.material",
            ),
        ),
    ]
