# Generated by Django 5.2 on 2025-12-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "supplier_portal",
            "0012_remove_supplierinvoice_note_supplierinvoice_subtotal_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierinvoice",
            name="stocked_in",
            field=models.BooleanField(default=False),
        ),
    ]
