# Generated by Django 5.2 on 2025-12-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accessories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accessoryitem",
            name="description",
        ),
        migrations.RemoveField(
            model_name="accessoryitem",
            name="price",
        ),
    ]
