# Generated by Django 5.2 on 2026-01-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_payment_method_order_shipping_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ngày giờ nhận hàng"
            ),
        ),
    ]
